# Generated by Django 2.1.5 on 2020-02-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banking',
            name='summary',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banking',
            name='tittle',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='banking',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
