# Generated by Django 2.1.5 on 2020-03-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0002_auto_20200226_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='ki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.TextField(max_length=50, null=True)),
            ],
        ),
    ]
