# Generated by Django 2.1.5 on 2020-03-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ki',
            name='tittle',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
