# Generated by Django 2.1.5 on 2020-03-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0005_auto_20200302_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ki',
            old_name='tittle',
            new_name='title',
        ),
    ]
