# Generated by Django 2.1.5 on 2020-03-03 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0006_auto_20200302_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='header',
            fields=[
                ('banking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Banking.Banking')),
                ('title', models.TextField(max_length=100, null=True)),
            ],
            bases=('Banking.banking',),
        ),
        migrations.DeleteModel(
            name='ki',
        ),
    ]
